// src/service-worker.js
import { precacheAndRoute } from 'workbox-precaching';

// Precache assets generated by the build process
// Their URLs are injected into the manifest variable below
// This variable must be present somewhere in your service worker file
precacheAndRoute(self.__WB_MANIFEST);

// Add custom service worker logic here (caching strategies, push notification handlers, etc.)
